python test\exercise_1_tester.py "build\exercise_1.exe" "test\sample_input\test0" "test\sample_output\wzor0"
python test\exercise_1_tester.py "build\exercise_1.exe" "test\sample_input\test1" "test\sample_output\wzor1"
python test\exercise_1_tester.py "build\exercise_1.exe" "test\sample_input\test2" "test\sample_output\wzor2"
python test\exercise_1_tester.py "build\exercise_1.exe" "test\sample_input\test3" "test\sample_output\wzor3"
python test\exercise_1_tester.py "build\exercise_1.exe" "test\sample_input\test4" "test\sample_output\wzor4"
python test\exercise_1_tester.py "build\exercise_1.exe" "test\sample_input\test5" "test\sample_output\wzor5"
